export const PermissaoUsuarioEnum = {
	VISUALIZAR: "VISUALIZAR_USUARIO",
	CRIAR: "CRIAR_USUARIO",
	EXCLUIR: "EXCLUIR_USUARIO",
};

export const PermissaoGrupoUsuarioEnum = {
	VISUALIZAR: "VISUALIZAR_GRUPO_USUARIO",
	CRIAR: "CRIAR_GRUPO_USUARIO",
	EXCLUIR: "EXCLUIR_GRUPO_USUARIO",
};

export const PermissaoCategoriaProdutoEnum = {
	VISUALIZAR: "VISUALIZAR_CATEGORIA_PRODUTO",
	CRIAR: "CRIAR_CATEGORIA_PRODUTO",
	EXCLUIR: "EXCLUIR_CATEGORIA_PRODUTO",
};

export const PermissaoTipoOcorrenciaEnum = {
	VISUALIZAR: "VISUALIZAR_TIPO_OCORRENCIA",
	CRIAR: "CRIAR_TIPO_OCORRENCIA",
	EXCLUIR: "EXCLUIR_TIPO_OCORRENCIA",
};

export const PermissaoTipoDocumentoEnum = {
	VISUALIZAR: "VISUALIZAR_TIPO_DOCUMENTO",
	CRIAR: "CRIAR_TIPO_DOCUMENTO",
	EXCLUIR: "EXCLUIR_TIPO_DOCUMENTO",
};

export const PermissaoEmpresaEnum = {
	VISUALIZAR: "VISUALIZAR_EMPRESA",
	CRIAR: "CRIAR_EMPRESA",
	EXCLUIR: "EXCLUIR_EMPRESA",
};

export const PermissaoMotoristaEnum = {
	VISUALIZAR: "VISUALIZAR_MOTORISTA",
	CRIAR: "CRIAR_MOTORISTA",
	EXCLUIR: "EXCLUIR_MOTORISTA",
};

export const PermissaoProdutoEnum = {
	VISUALIZAR: "VISUALIZAR_PRODUTO",
	CRIAR: "CRIAR_PRODUTO",
	EXCLUIR: "EXCLUIR_PRODUTO",
};

export const PermissaoVeiculoEnum = {
	VISUALIZAR: "VISUALIZAR_VEICULO",
	CRIAR: "CRIAR_VEICULO",
	EXCLUIR: "EXCLUIR_VEICULO",
};

export const PermissaoModeloVeiculoEnum = {
	VISUALIZAR: "VISUALIZAR_MODELO_VEICULO",
	CRIAR: "CRIAR_MODELO_VEICULO",
	EXCLUIR: "EXCLUIR_MODELO_VEICULO",
};

export const PermissaoCargaEnum = {
	VISUALIZAR: "VISUALIZAR_CARGA",
	CRIAR: "CRIAR_CARGA",
	EXCLUIR: "EXCLUIR_CARGA",
};

export const PermissaoContatoChaveEmpresaEnum = {
	VISUALIZAR: "VISUALIZAR_CONTATO_CHAVE_EMPRESA",
	CRIAR: "CRIAR_CONTATO_CHAVE_EMPRESA",
	EXCLUIR: "EXCLUIR_CONTATO_CHAVE_EMPRESA",
};

export const PermissaoAduanaEnum = {
	VISUALIZAR: "VISUALIZAR_ADUANA",
	CRIAR: "CRIAR_ADUANA",
	EXCLUIR: "EXCLUIR_ADUANA",
};

export const PermissaoPedagioEnum = {
	VISUALIZAR: "VISUALIZAR_PEDAGIO",
	CRIAR: "CRIAR_PEDAGIO",
	EXCLUIR: "EXCLUIR_PEDAGIO",
};

export const PermissaoPostoCombustivelEnum = {
	VISUALIZAR: "VISUALIZAR_POSTO_COMBUSTIVEL",
	CRIAR: "CRIAR_POSTO_COMBUSTIVEL",
	EXCLUIR: "EXCLUIR_POSTO_COMBUSTIVEL",
};

export const PermissaoUnidadeEnum = {
	VISUALIZAR: "VISUALIZAR_UNIDADE",
	CRIAR: "CRIAR_UNIDADE",
	EXCLUIR: "EXCLUIR_UNIDADE",
};
